<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Bcc' => 'Скрытая копия (bcc)',
    'Cannot send message without a recipient' => 'Нельзя отправлять сообщения без получателей',
    'Cc' => 'Копия (cc)',
    'Code' => 'Код',
    'Create new message' => 'Создать новое сообщение',
    'Create new template' => 'Создать новый шаблон',
    'Created at' => 'Создано',
    'Current application name' => 'Название приложения',
    'Description' => 'Описание',
    'Domain of current site' => 'Домен текущего сайта',
    'Edit message' => 'Редактировать сообщение',
    'Edit template' => 'Редактировать шаблон',
    'Email' => 'Email',
    'Emergency response' => 'Нерпедвиденный ответ',
    'Failed to find message' => 'Неудалось найти сообщение',
    'Failed to send message' => 'Неудалось отправить сообщение',
    'General information' => 'Основная информация',
    'HTML content' => 'HTML версия',
    'Http host of current site' => 'Http хост текущего сайта',
    'ID' => 'ID',
    'ID of current user' => 'ID пользователя',
    'Key' => 'Ключ',
    'Limit exceeded retries' => 'Превышено число попыток отправки письма',
    'Message successfully saved' => 'Сообщение успешно сохранено',
    'Message templates management' => 'Управление шаблонами сообщений',
    'Messages' => 'Сообщения',
    'Messages list' => 'Список сообщений',
    'Messages management' => 'Управление сообщениями',
    'Messages not found' => 'Сообщения не найдены',
    'Name' => 'Имя',
    'Name of current user' => 'Имя пользователя',
    'New address' => 'Новый адрес',
    'New parameter' => 'Новый параметр',
    'Not specified message to edit.' => 'Не указано сообщение для редактирования.',
    'Not specified template to edit.' => 'Не указан шаблон для редактирования.',
    'Parameters' => 'Параметры',
    'Plain content' => 'Текстовая версия',
    'Postman' => 'Postman',
    'Remove message' => 'Удалить сообщение',
    'Remove template' => 'Удалить шаблон',
    'Removed messages' => 'Удалённые сообщения',
    'Removed templates' => 'Удалённые шаблоны',
    'Reply to' => 'Ответить (reply to)',
    'Resent message' => '',
    'Restore message' => 'Восстановить сообщение',
    'Restore template' => 'Восстановить шаблон',
    'Scheduled at' => 'Запланировано',
    'Select type' => 'Выберите тип',
    'Sending error' => 'Ошибка отправки сообщения',
    'Sent at' => 'Отправлено',
    'Subject' => 'Заголовок',
    'Subject of current letter' => 'Заголовок письма',
    'Template successfully saved' => 'Шаблон успешно сохранён',
    'Templates' => 'Шаблоны',
    'Templates list' => 'Список шаблонов',
    'Templates not found' => 'Шаблон не найден',
    'To' => 'Кому (to)',
    'Unable to determine the id of the message' => 'Неудалось определить id сообщения',
    'Updated at' => 'Обновлено',
    'Use layout' => 'Использовать стандартный шаблон (layout)',
];
