<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Failed to bring the resource directory of uploaded files.' => 'Не удалось перенести загруженный ресурс в директорию upload',
    'Media module not configured' => 'Модуль media не сконфигурирован',
    'Storage directory not available for reading (Media::$storagePath).' => 'Директория с кэшем модифицированных файлов недоступна для чтения (Media::$storagePath).',
    'Storage directory not available for writing (Media::$storagePath).' => 'Директория с кэшем модифицированных файлов недоступна для записи (Media::$storagePath).',
    'Unable to determine the path to the storage directory (Media::$storagePath).' => 'Не удалось определить директория для кэша модифицированных файлов (Media::$storagePath).',
    'Unable to determine the path to the upload directory (Media::$uploadPath).' => 'Не удалось определить директория для загруженных файлов (Media::$uploadPath).',
    'Upload directory not available for reading (Media::$uploadPath).' => 'Директория upload недоступна для чтения (Media::$uploadPath).',
    'Upload directory not available for writing (Media::$uploadPath).' => 'Директория upload недоступна для записи (Media::$uploadPath).',
];
