<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account is not activated.' => '',
    'Account not found.' => '',
    'Account removed.' => '',
    'Account successfully saved' => '',
    'Accounts' => '',
    'Accounts list' => '',
    'Accounts management' => '',
    'Accounts not found' => '',
    'Approve new password' => '',
    'Cancel' => '',
    'Clients' => '',
    'Create new account' => '',
    'Create new property' => '',
    'Created at' => '',
    'Delete' => '',
    'Edit account' => '',
    'Email' => '',
    'Email with instructions sent.' => '',
    'Feeds' => '',
    'Fill attributes' => '',
    'Filter' => '',
    'Forgot password' => '',
    'Form errors.' => '',
    'General information' => '',
    'I agree to the terms of use' => '',
    'I agree to the {terms} of use' => '',
    'I forgot my password' => '',
    'ID' => '',
    'Key' => '',
    'Messages' => '',
    'Name' => '',
    'New password' => '',
    'No properties.' => '',
    'Not specified account to edit.' => '',
    'Password' => '',
    'Password approve' => '',
    'Postman' => '',
    'Properties' => '',
    'Property successfully saved' => '',
    'Property was successfully removed' => '',
    'Provider for client `{client}` bot found.' => '',
    'Remember me' => '',
    'Remove account' => '',
    'Removed accounts' => '',
    'Reset password' => '',
    'Restore account' => '',
    'Roles' => '',
    'Roles successfully saved.' => '',
    'Save' => '',
    'Save and create new property' => '',
    'Save and edit property' => '',
    'Search' => '',
    'Sign In' => '',
    'Sign Up' => '',
    'Sign in' => '',
    'Sign up' => '',
    'Sing in' => '',
    'Sing up' => '',
    'Templates' => '',
    'To complete the registration you must specify your email' => '',
    'Unable to remove a property' => '',
    'Unknown error' => '',
    'Unknown error.' => '',
    'Updated at' => '',
    'User' => '',
    'Username' => '',
    'Value' => '',
    'Welcome!' => '',
    'When executing a query the error occurred' => '',
    'You must accept the terms' => '',
    'terms' => '',
    '{attribute} not found.' => '',
    'Женщина' => '',
    'Мужчина' => '',
];
