<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to index' => 'Вернуться на главную',
    'Dashboard' => 'Рабочий стол',
    'Error' => 'Ошибка',
    'Error {number}' => 'Ошибка {number}',
    'Meanwhile, you may {return to dashboard}.' => 'Пока что Вы можете {return to dashboard}.',
    'Need configurate admin role in account module.' => '',
    'Need configurate user role in account module.' => '',
    'Profile' => 'Профиль',
    'Sign in' => 'Вход',
    'Sign out' => 'Выход',
    'Sign up' => 'Регистрация',
    'Terms of use' => 'Правила использования',
    'We will work on fixing that right away.' => 'В данный момент мы работает над устранением проблемы.',
    'return to dashboard' => 'вернуться на рабочий стол',
];
