<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Account created successfully' => '',
    'Account unlink successfully' => '',
    'Cancel' => '',
    'Client' => '',
    'Client successfully saved' => '',
    'Clients list' => '',
    'Clients management' => '',
    'Clients not found' => '',
    'Create new client' => '',
    'Create new property' => '',
    'Created at' => '',
    'Delete' => '',
    'Edit client' => '',
    'Email' => '',
    'Failed to create account' => '',
    'Failed to unlink account' => '',
    'Filter' => '',
    'General information' => '',
    'ID' => '',
    'Key' => '',
    'Name' => '',
    'No bound Account' => '',
    'No properties.' => '',
    'Not specified client to edit.' => '',
    'Phone' => '',
    'Properties' => '',
    'Property successfully saved' => '',
    'Property was successfully removed' => '',
    'Remove client' => '',
    'Removed clients' => '',
    'Restore client' => '',
    'Save' => '',
    'Save and create new property' => '',
    'Save and edit property' => '',
    'Search' => '',
    'Unable to remove a property' => '',
    'Unknown error' => '',
    'Updated at' => '',
    'Username' => '',
    'Value' => '',
    'When executing a query the error occurred' => '',
    'You can not create an account from unsaved client.' => '',
];
