<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A colorful description section' => 'Доходчивое описание раздела',
    'Create new item' => 'Создань новый элемент',
    'Create new section' => 'Создать новый раздел',
    'Edit item' => 'Редактировать элемент',
    'Edit section' => 'Редактировать раздел',
    'End publishing at' => 'Дата окончания публикации',
    'Feeds' => 'Лента информации',
    'General information' => 'Основная информация',
    'Item successfully saved' => 'Элемент успешно сохранён',
    'Items list' => 'Список элементов',
    'Items not found' => 'Элемент не найден',
    'Marketing title' => 'Маркетинговое название',
    'Meta description' => 'Meta описание (description)',
    'Meta keywords' => 'Meta ключевые слова (keywords)',
    'Meta title' => 'Meta заголовок (title)',
    'Not specified item to edit.' => 'Не указан элемент для редактирвоания',
    'Not specified section to edit.' => 'Не указан раздел для редактирвоания',
    'Parent section' => 'Родительский раздел',
    'Remove item' => 'Удалить элемент',
    'Remove section' => 'Удалить раздел',
    'Removed items' => 'Удалённые элементы',
    'Restore item' => 'Восстановить элемент',
    'Restore section' => 'Восстановить раздел',
    'Section successfully saved' => 'Раздел успешно сохранён',
    'Sections' => 'Разделы',
    'Sections management' => 'Управление разделами',
    'Slug' => 'Заголовок в url',
    'Some title...' => 'Какой-то заголовок...',
    'Sort' => 'Сортировка',
    'Start publishing at' => 'Дата начала публикации',
    'Title' => 'Заголовок',
    'keyword, password, handball' => 'дверь, доска, наличник',
    'some-title' => 'some-title',
];
