<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Отмена',
    'Changes not saved yet' => 'Изменения ещё не сохранены',
    'Filter' => 'Фильтр',
    'Model must be `{class}`' => '',
    'Model must be `{class}`.' => 'Модель должна быть `{class}`',
    'Model must contain an attribute `{attribute}`.' => 'Модель должна содержать атрибут `{class}`',
    'Recommended {refresh} the page.' => 'Рекомендуется {refresh} страницу.',
    'Refresh' => 'Обновить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'The data of this item has been changed.' => 'Данные на странице устарели.',
    'Unknown error' => 'Непредвиденная ошибка',
    'Warning' => 'Внимание',
    'When executing a query the error occurred' => 'При обработке запроса произошла ошибка',
];
