<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Аккаунт',
    'Account created successfully' => 'Аккаунт успешно создан',
    'Account unlink successfully' => 'Аккаунт успешно отвязан',
    'Client' => 'Клиент',
    'Client successfully saved' => 'Клиент успешно сохранён',
    'Clients' => 'Клиенты',
    'Clients list' => 'Список клиентов',
    'Clients management' => 'Управление клиентами',
    'Clients not found' => 'Клиент не найден',
    'Create new client' => 'Создать нового клиента',
    'Create new property' => 'Создать новое свойство',
    'Created at' => 'Создано',
    'Delete' => 'Удалить',
    'Edit client' => 'Редактировать клиента',
    'Email' => 'Email',
    'Failed to create account' => 'Ошибка создания аккаунта',
    'Failed to unlink account' => 'Ошибка отвязывания аккаунта',
    'General information' => '',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Name' => 'Имя',
    'No bound Account' => 'Нет привязаного аккаунта',
    'No properties.' => 'Нет свойств',
    'Not specified client to edit.' => '',
    'Phone' => 'Телефон',
    'Properties' => 'Свойства',
    'Property successfully saved' => 'Свойство успешно сохранено',
    'Property was successfully removed' => 'Свойство успешно удалено',
    'Remove client' => 'Удалить клиента',
    'Removed clients' => 'Удалённые клиенты',
    'Restore client' => 'Восстановить клиента',
    'Save and create new property' => 'Сохранить и перейти к созданию нового свойства',
    'Save and edit property' => 'Сохранить и перейти обратно к редактированию свойства',
    'Unable to remove a property' => 'Невозможно удалить свойство',
    'Updated at' => 'Обновлено',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'You can not create an account from unsaved client.' => 'Вы не можете создать аккаунт из несохранённого клиента.',
];
