<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A colorful description section' => 'Описание раздела',
    'Content' => 'Контент',
    'Create new page' => 'Создать новую страницу',
    'Edit page' => 'Редактировать страницу',
    'General information' => 'Основная информация',
    'ID' => 'ID',
    'Marketing title' => 'Маркетинговый заголовок',
    'Meta description' => 'Meta описание (description)',
    'Meta keywords' => 'Meta ключевые слова (keywords)',
    'Meta title' => 'Meta заголовок (title)',
    'Not specified page to edit.' => 'Не задана страница для редактирования',
    'Page not found' => 'Страница не найдена',
    'Page successfully saved' => 'Страница успешно сохранена',
    'Pages' => 'Страницы',
    'Pages list' => 'Список страниц',
    'Pages management' => 'Управление страницами',
    'Pages not found' => 'Страницы не найдены',
    'Remove page' => 'Удалить страницу',
    'Removed pages' => 'Удалённые страницы',
    'Restore page' => 'Восстановить страницу',
    'Slug' => 'Заголовок в url',
    'Some title...' => 'Какой-то заголовок...',
    'Title' => 'Заголовок',
    'Updated at' => 'Дата обновления',
    'keyword, password, handball' => '',
    'some-title' => 'Введите заголовок',
];
