<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account is not activated.' => 'Аккаунт не активирован',
    'Account not found.' => 'Пользователь не найден',
    'Account removed.' => 'Пользователь удален',
    'Account successfully saved' => 'Пользователь успешно сохранен',
    'Accounts' => 'Пользователи',
    'Accounts list' => 'Список пользователей',
    'Accounts management' => 'Управление пользователями',
    'Accounts not found' => 'Пользователь не найден',
    'Approve new password' => 'Повторите пароль',
    'Create new account' => 'Создать нового пользователя',
    'Create new property' => 'Создать новое свойство',
    'Created at' => 'Дата создания',
    'Delete' => 'Удалить',
    'Edit account' => 'Редактировать пользователя',
    'Email' => 'Email',
    'Email with instructions sent.' => 'Email с инструкциями отправлен',
    'Female' => 'Женщина',
    'Fill attributes' => 'Заполните поля',
    'Forgot password' => 'Забыл пароль',
    'Form errors.' => 'Ошибки формы',
    'General information' => 'Основная информация',
    'I agree to the terms of use' => 'Я соглашаюсь с условиями',
    'I agree to the {terms} of use' => 'Я соглашаюсь с {terms}',
    'I forgot my password' => 'Я забыл мой пароль',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Male' => 'Мужчина',
    'Name' => 'Имя',
    'New password' => 'Новый пароль',
    'No properties.' => 'Нет свойств',
    'Not specified account to edit.' => 'Не задан пользователь для редактирования',
    'Password' => 'Пароль',
    'Password approve' => 'Повторите пароль',
    'Properties' => 'Свойства',
    'Property successfully saved' => 'Свойство успешно сохранено',
    'Property was successfully removed' => 'Свойство успешно удалено',
    'Provider for client `{client}` not found.' => 'Провайдер для клиента `{client}` не найден.',
    'Remember me' => 'Запомнить меня',
    'Remove account' => 'Удалить пользователя',
    'Removed accounts' => 'Удаленные пользователи',
    'Reset password' => 'Сбросить пароль',
    'Restore account' => 'Восстановить пользователя',
    'Roles' => 'Роли',
    'Roles successfully saved.' => 'Роли успешно сохранены',
    'Save' => 'Сохранить',
    'Save and create new property' => 'Сохранить и создать новое свойство',
    'Save and edit property' => 'Сохранить и редактировать свойство',
    'Sign in' => 'Войти',
    'Sign up' => 'Зарегистрироваться',
    'To complete the registration you must specify your email' => 'Подтвердите email для окончания регистрации',
    'Unable to remove a property' => 'Невозможно удалить свойство',
    'Updated at' => 'Дата обновления',
    'User' => 'Пользователь',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'Welcome!' => 'Добро пожаловать',
    'You must accept the terms' => 'Вы должны подтвердить условия',
    'terms' => 'правила',
    '{attribute} not found.' => '{attribute} не найден.',
];
