<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Failed to bring the resource directory of uploaded files.' => '',
    'Media must be an instance of `cookyiimodulesMediaesourcesMedia`' => '',
    'Storage directory not available for reading (Media::$storagePath).' => '',
    'Storage directory not available for writing (Media::$storagePath).' => '',
    'Unable to determine the path to the storage directory (Media::$storagePath).' => '',
    'Unable to determine the path to the upload directory (Media::$uploadPath).' => '',
    'Upload directory not available for reading (Media::$uploadPath).' => '',
    'Upload directory not available for writing (Media::$uploadPath).' => '',
];
