<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Bcc' => '',
    'Cc' => '',
    'Code' => '',
    'Create new message' => '',
    'Create new template' => '',
    'Created at' => '',
    'Description' => '',
    'Edit Message' => '',
    'Edit message' => '',
    'Edit template' => '',
    'Email' => '',
    'Error' => '',
    'Filter' => '',
    'General information' => '',
    'HTML content' => '',
    'ID' => '',
    'Key' => '',
    'Message successfully saved' => '',
    'Message templates management' => '',
    'Messages management' => '',
    'Messages not found' => '',
    'Name' => '',
    'New address' => '',
    'New parameter' => '',
    'Not specified message to edit.' => '',
    'Not specified template to edit.' => '',
    'Parameters' => '',
    'Plain content' => '',
    'Remove message' => '',
    'Remove template' => '',
    'Removed messages' => '',
    'Removed templates' => '',
    'Reply to' => '',
    'Resent message' => '',
    'Restore message' => '',
    'Restore template' => '',
    'Scheduled at' => '',
    'Select type' => '',
    'Sent at' => '',
    'Subject' => '',
    'Subject ' => '',
    'Template successfully saved' => '',
    'Templates list' => '',
    'Templates not found' => '',
    'To' => '',
    'Unknown error' => '',
    'Updated at' => '',
    'Use layout' => '',
    'When executing a query the error occurred' => '',
];
