<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A colorful description section' => '',
    'Cancel' => '',
    'Content' => '',
    'Create new page' => '',
    'Edit page' => '',
    'Filter' => '',
    'General information' => '',
    'ID' => '',
    'Marketing title' => '',
    'Meta description' => '',
    'Meta keywords' => '',
    'Meta title' => '',
    'Not specified page to edit.' => '',
    'Page successfully saved' => '',
    'Pages' => null,
    'Pages list' => '',
    'Pages management' => '',
    'Pages not found' => '',
    'Remove page' => '',
    'Removed pages' => '',
    'Restore page' => '',
    'Save' => '',
    'Search' => '',
    'Slug' => '',
    'Some title...' => '',
    'Title' => '',
    'Unknown error' => '',
    'Updated at' => '',
    'When executing a query the error occurred' => '',
    'keyword, password, handball' => '',
    'some-title' => '',
    'Страница не найдена' => '',
];
