#!/bin/bash

openssl genrsa -des3 -out .ssl/$1.key 1024
openssl req -new -key .ssl/$1.key -out .ssl/$1.csr
cp .ssl/$1.key .ssl/$1.key.org
openssl rsa -in .ssl/$1.key.org -out .ssl/$1.key
openssl x509 -req -days 365 -in .ssl/$1.csr -signkey .ssl/$1.key -out .ssl/$1.crt