#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$baseDir = realpath(__DIR__ . '/..');

require($baseDir . '/vendor/autoload.php');

require($baseDir . '/backend-app/credentials.php');
require($baseDir . '/env.php');

cookyii\Config::requireGlobals($baseDir);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require($baseDir . '/vendor/yiisoft/yii2/Yii.php');
require($baseDir . '/common/config/aliases.php');

cookyii\Config::init('backend', 'console');

exit((new yii\console\Application(cookyii\Config::$config))
    ->run());
